import turtle
window = turtle.Screen()
bob = turtle.Turtle()
bob.right(90)
bob.forward(50)
bob.left(90)
bob.forward(50)
bob.left(90)
bob.forward(50)
bob.left(90)
bob.forward(50)
#Triangle above the house
bob.right(120)
bob.forward(50)
bob.right(120)
bob.forward(50)
window.exitonclick()
